[project]
name = "delta-sharing-rs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.4",
]

[tool.uv]
package = false
